import streamlit as st
import sys
import os
import pandas as pd
import random
import textwrap
import time
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

# --- 1. PATH SETUP ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
sys.path.append(project_root)

# --- CLOUD DEPLOYMENT SETUP (CRITICAL) ---
# This ensures the database is built when deployed to Streamlit Cloud
chroma_db_path = os.path.join(project_root, 'data', 'chroma_db')

if not os.path.exists(chroma_db_path):
    st.warning("⚙️ First-time setup: Building the Knowledge Base... (This takes ~1 minute)")
    
    # Add scripts folder to path to import vector engine
    scripts_path = os.path.join(project_root, 'scripts')
    sys.path.append(scripts_path)
    
    try:
        # Run the builder script
        from scripts.vector_engine import build_vector_db
        build_vector_db()
        st.success("✅ Knowledge Base Built! Refreshing...")
        time.sleep(2)
        st.rerun()
    except Exception as e:
        st.error(f"Setup Failed: {e}")
        # Try to continue anyway, in case it's a false negative
        pass

# Import Backend
try:
    from backend.rag_engine import generate_answer
except ImportError:
    st.error("⚠️ Backend not found. Please ensure you are in the project root.")

# Define paths
FONT_PATH = os.path.join(current_dir, 'font.ttf')
DATA_PATH = os.path.join(project_root, 'data', 'gita_verses.csv')

# --- 2. PAGE CONFIG ---
st.set_page_config(
    page_title="Saarthi (सारथी) 2.0",
    page_icon="🕉️",
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- 3. HELPER: THEMED WISDOM CARDS ---
def create_quote_image(text, theme="Mystic Blue"):
    img_width, img_height = 800, 800
    
    # Enhanced Theme Color Maps with richer palettes
    themes = {
        "Mystic Blue": ((15, 23, 42), (88, 28, 135)),           # Deep slate to purple
        "Saffron Sunset": ((255, 107, 0), (220, 38, 38)),       # Vibrant orange to red
        "Forest Peace": ((5, 46, 22), (34, 197, 94)),           # Dark to bright green
        "Galaxy Void": ((0, 0, 0), (109, 40, 217)),             # Black to vivid purple
        "Golden Temple": ((180, 83, 9), (234, 179, 8)),         # Bronze to gold
        "Lotus Pink": ((157, 23, 77), (236, 72, 153))           # Deep to bright pink
    }
    
    top_color, bottom_color = themes.get(theme, themes["Mystic Blue"])

    img = Image.new('RGB', (img_width, img_height), top_color)
    draw = ImageDraw.Draw(img)

    # Smooth gradient
    for y in range(img_height):
        r = int(top_color[0] + (bottom_color[0] - top_color[0]) * y / img_height)
        g = int(top_color[1] + (bottom_color[1] - top_color[1]) * y / img_height)
        b = int(top_color[2] + (bottom_color[2] - top_color[2]) * y / img_height)
        draw.line([(0, y), (img_width, y)], fill=(r, g, b))

    # Add decorative elements
    draw.ellipse([50, 50, 150, 150], outline=(255, 215, 0, 100), width=3)
    draw.ellipse([650, 650, 750, 750], outline=(255, 215, 0, 100), width=3)

    try:
        font_large = ImageFont.truetype(FONT_PATH, 44)
        font_small = ImageFont.truetype(FONT_PATH, 26)
        font_header = ImageFont.truetype(FONT_PATH, 36)
    except:
        font_large = ImageFont.load_default()
        font_small = ImageFont.load_default()
        font_header = ImageFont.load_default()

    clean_text = text.replace("**", "").replace("###", "").replace(":", "")
    if len(clean_text) > 280: clean_text = clean_text[:280] + "..."
    wrapper = textwrap.TextWrapper(width=28) 
    word_list = wrapper.wrap(text=clean_text)

    margin = 80
    current_h = 140
    draw.text((margin, 60), "🕉️ SAARTHI WISDOM", fill=(255, 215, 0), font=font_header)

    for line in word_list:
        draw.text((margin, current_h), line, font=font_large, fill=(255, 255, 255))
        bbox = font_large.getbbox(line)
        line_height = bbox[3] if bbox else 20
        current_h += line_height + 18 

    draw.text((margin, img_height - 90), "✨ Generated by Saarthi AI", fill=(220, 220, 220), font=font_small)

    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()

@st.cache_data(ttl=3600)
def get_random_shloka():
    if not os.path.exists(DATA_PATH): return None
    try:
        df = pd.read_csv(DATA_PATH)
        if df.empty: return None
        row = df.sample(1).iloc[0]
        return {"text": str(row['sanskrit']).strip(), "meaning": str(row['translation']), "ref": f"Gita {row['chapter']}.{row['verse']}"}
    except: return None

# --- 4. ENHANCED CSS STYLING ---
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Crimson+Pro:wght@300;400;600&family=Playfair+Display:wght@700&family=Inter:wght@300;400;600&display=swap');

/* Main Background with Animated Gradient */
.stApp { 
    background: linear-gradient(-45deg, #fff5e6, #ffe4f0, #f3e8ff, #fef3c7);
    background-size: 400% 400%;
    animation: gradientShift 15s ease infinite;
}

@keyframes gradientShift {
    0% { background-position: 0% 50%; }
    50% { background-position: 100% 50%; }
    100% { background-position: 0% 50%; }
}

/* Typography */
h1, h2, h3, h4 { font-family: 'Cinzel', serif !important; color: #1e293b !important; }
p, span, div { font-family: 'Crimson Pro', serif !important; }
.stChatMessage p, .stMarkdown p { color: #1e293b !important; font-size: 1.1rem; line-height: 1.8; }

/* Chat Messages */
.stChatMessage { 
    border-radius: 20px; padding: 20px !important; margin: 15px 0 !important;
    box-shadow: 0 8px 24px rgba(0,0,0,0.12); backdrop-filter: blur(10px);
    border: 1px solid rgba(255,255,255,0.3);
}
.stChatMessage.user { background: linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%) !important; border-left: 5px solid #f97316; }
.stChatMessage.assistant { background: linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%) !important; border-left: 5px solid #9333ea; }

/* Header Box */
.header-box { 
    background: linear-gradient(135deg, #0f172a 0%, #5b21b6 50%, #7c3aed 100%);
    padding: 40px; border-radius: 24px; text-align: center; margin-bottom: 30px;
    box-shadow: 0 20px 40px rgba(124, 58, 237, 0.3); position: relative; overflow: hidden;
}
.header-box::before {
    content: ''; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%;
    background: radial-gradient(circle, rgba(255,255,255,0.1) 0%, transparent 70%);
    animation: pulse 8s ease-in-out infinite;
}
@keyframes pulse { 0%, 100% { transform: translate(0, 0); } 50% { transform: translate(10%, 10%); } }
.header-title { color: white !important; font-size: 3rem; font-weight: 700; font-family: 'Playfair Display', serif !important; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); position: relative; }
.header-subtitle { color: #e2e8f0 !important; font-size: 1.1rem; font-style: italic; margin-top: 10px; position: relative; }

/* Sidebar Enhancement */
[data-testid="stSidebar"] { background: linear-gradient(180deg, #fafaf9 0%, #f5f3ff 100%); border-right: 2px solid #e9d5ff; }
[data-testid="stSidebar"] label, [data-testid="stSidebar"] p, [data-testid="stSidebar"] span { color: #1e293b !important; font-weight: 500; }

/* Breathing Circle */
@keyframes breathe {
    0% { transform: scale(1); opacity: 0.7; box-shadow: 0 0 20px rgba(251, 191, 36, 0.4); }
    50% { transform: scale(1.25); opacity: 1; box-shadow: 0 0 60px rgba(251, 191, 36, 0.8); }
    100% { transform: scale(1); opacity: 0.7; box-shadow: 0 0 20px rgba(251, 191, 36, 0.4); }
}
.breathing-circle {
    width: 180px; height: 180px; background: linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%);
    border-radius: 50%; margin: 0 auto; animation: breathe 4s infinite ease-in-out;
    display: flex; align-items: center; justify-content: center;
    color: #78350f; font-weight: bold; font-size: 1.3rem; font-family: 'Inter', sans-serif;
}

/* Button & Inputs */
.stButton > button { border-radius: 12px; font-weight: 600; padding: 12px 24px; transition: all 0.3s ease; border: none; box-shadow: 0 4px 12px rgba(0,0,0,0.15); }
.stButton > button:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.25); }
.stProgress > div > div > div { background: linear-gradient(90deg, #f97316 0%, #ea580c 100%); }
.stChatInputContainer { border-radius: 16px; box-shadow: 0 8px 24px rgba(0,0,0,0.12); }
.card-studio-box { background: linear-gradient(135deg, #fefce8 0%, #fef3c7 100%); padding: 20px; border-radius: 16px; border: 2px solid #fbbf24; margin-top: 20px; }
</style>
""", unsafe_allow_html=True)

# --- 5. SIDEBAR: SADHANA & SETTINGS ---
with st.sidebar:
    col1, col2, col3 = st.columns([1,2,1])
    with col2:
        st.markdown("""<div style='text-align: center; padding: 20px;'><div style='font-size: 4rem;'>🕉️</div><h2 style='color: #5b21b6; margin-top: 10px;'>Saarthi 2.0</h2></div>""", unsafe_allow_html=True)
    st.divider()
    st.markdown("### 🔥 My Sadhana Journey")
    st.progress(70)
    st.caption("**Day 7 of 10:** 'Conquering Anger' 💪")
    st.markdown("*Keep going, warrior!*")
    st.divider()
    st.markdown("### ⚙️ Preferences")
    language = st.radio("🌐 Language:", ["English", "Hindi"])
    mode = st.radio("📖 Depth Level:", ["Beginner", "Scholar"])
    st.divider()
    st.markdown("### 🎯 Focus Area")
    focus_options = {"General": "🌟", "Relationships": "💞", "Work/Career": "💼", "Self-Growth": "🌱"}
    focus = st.selectbox("I am exploring:", list(focus_options.keys()), format_func=lambda x: f"{focus_options[x]} {x}")
    st.divider()
    daily = get_random_shloka()
    if daily:
        st.markdown("### ✨ Daily Wisdom")
        st.info(f"*{daily['text']}*\n\n— {daily['ref']}")
    st.divider()
    st.markdown("""<div style='text-align: center; padding: 20px; opacity: 0.7;'><small>Made with 💜 for spiritual seekers</small></div>""", unsafe_allow_html=True)

# --- 6. MAIN HEADER & SOS BUTTON ---
col_head, col_sos = st.columns([4, 1])
with col_head:
    st.markdown("""<div class="header-box"><div class="header-title">🕉️ Saarthi सारथी</div><div class="header-subtitle">Your Divine Companion for Dharma • Artha • Kama • Moksha</div></div>""", unsafe_allow_html=True)
with col_sos:
    st.write("")
    st.write("")
    if st.button("🆘 CALM NOW", type="primary", use_container_width=True, help="Start 2-minute pranayama"):
        st.session_state.calm_mode = True

# --- 7. BREATHING MODE (OVERLAY) ---
if st.session_state.get("calm_mode", False):
    st.markdown("""<div style='background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); padding: 40px; border-radius: 24px; text-align: center; box-shadow: 0 20px 40px rgba(251, 191, 36, 0.3);'><h2 style='color: #78350f;'>🧘 Pranayama - Instant Calm</h2><p style='color: #92400e; font-size: 1.1rem;'>Follow the breath, find your center</p></div>""", unsafe_allow_html=True)
    placeholder = st.empty()
    bar = st.progress(0)
    breath_phases = [("Inhale...", "#fbbf24", "scale(1.2)"), ("Hold...", "#818cf8", "scale(1.3)"), ("Exhale...", "#34d399", "scale(0.9)")]
    for i in range(1, 4):
        for phase_name, phase_color, phase_scale in breath_phases:
            placeholder.markdown(f"""<div style="text-align:center; padding: 40px;"><h3 style='color: #78350f; margin-bottom: 30px;'>Cycle {i} of 3</h3><div class="breathing-circle" style="background: linear-gradient(135deg, {phase_color}, {phase_color}dd); transform: {phase_scale};">{phase_name}</div></div>""", unsafe_allow_html=True)
            time.sleep(4)
        bar.progress(i * 33)
    st.success("✨ You are calm. You are strong. Return to your duty with clarity.")
    if st.button("🙏 Close", use_container_width=True):
        st.session_state.calm_mode = False
        st.rerun()

# --- 8. CHAT INTERFACE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

if not st.session_state.messages and not st.session_state.get("calm_mode", False):
    st.markdown(f"""<div style='text-align: center; padding: 30px; margin: 20px 0;'><h3 style='color: #5b21b6;'>🧭 Begin Your Journey ({focus_options[focus]} {focus})</h3><p style='color: #64748b; font-size: 1.1rem;'>Choose a path or ask your own question</p></div>""", unsafe_allow_html=True)
    c1, c2, c3 = st.columns(3)
    if focus == "Relationships": prompts = [("💔", "Handle family conflict?"), ("👨‍👩‍👧", "Duties of a parent?"), ("🤝", "Build better bonds?")]
    elif focus == "Work/Career": prompts = [("💪", "Overcome failure?"), ("👑", "Leadership wisdom?"), ("🎯", "Stay focused?")]
    elif focus == "Self-Growth": prompts = [("🌱", "Start meditation?"), ("😌", "Find inner peace?"), ("🔥", "Build discipline?")]
    else: prompts = [("☮️", "Find mental peace?"), ("♻️", "Understand karma?"), ("🧘", "Begin meditation?")]
    for col, (emoji, text) in zip([c1, c2, c3], prompts):
        with col:
            if st.button(f"{emoji}\n\n**{text}**", use_container_width=True, key=text):
                st.session_state.messages.append({"role": "user", "content": text})
                st.rerun()

for msg in st.session_state.messages:
    avatar = "https://api.dicebear.com/7.x/avataaars/svg?seed=user" if msg["role"] == "user" else "https://api.dicebear.com/7.x/bottts/svg?seed=saarthi&backgroundColor=b6e3f4"
    with st.chat_message(msg["role"], avatar=avatar):
        st.markdown(msg["content"])

if prompt := st.chat_input("💭 Ask Saarthi anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.rerun()

if st.session_state.messages and st.session_state.messages[-1]["role"] == "user":
    with st.chat_message("assistant", avatar="https://api.dicebear.com/7.x/bottts/svg?seed=saarthi&backgroundColor=b6e3f4"):
        with st.spinner("🔮 Consulting the sacred texts..."):
            history = [{"role": m["role"], "content": m["content"]} for m in st.session_state.messages]
            answer, sources = generate_answer(st.session_state.messages[-1]["content"], history[:-1], mode=mode, language=language, focus=focus)
            full_response = answer
            if sources:
                header = "\n\n---\n\n**📚 Sacred References:**\n"
                full_response += header + "\n".join([f"• {s}" for s in sources])
            st.markdown(full_response)
    st.session_state.messages.append({"role": "assistant", "content": full_response})
    st.rerun()

# --- 9. PERSISTENT CARD GENERATOR ---
if st.session_state.messages and st.session_state.messages[-1]["role"] == "assistant":
    last_response = st.session_state.messages[-1]["content"]
    st.markdown("<hr>", unsafe_allow_html=True)
    st.markdown("""<div class='card-studio-box'><h3 style='color: #78350f; text-align: center; margin-bottom: 20px;'>🎴 Wisdom Card Studio</h3><p style='text-align: center; color: #92400e;'>Create beautiful cards to share this wisdom</p></div>""", unsafe_allow_html=True)
    st.write("")
    c_theme, c_btn = st.columns([3, 2])
    with c_theme:
        theme_choice = st.selectbox("🎨 Choose Your Theme:", ["Mystic Blue", "Saffron Sunset", "Forest Peace", "Galaxy Void", "Golden Temple", "Lotus Pink"], help="Select a color palette for your wisdom card")
    with c_btn:
        st.write("")
        card_text = last_response.split("**📚 Sacred References:**")[0].strip()
        card_text = card_text.split("**📚 Reference:**")[0].strip()
        card_bytes = create_quote_image(card_text, theme=theme_choice)
        st.download_button(label="📥 Download Card", data=card_bytes, file_name=f"saarthi_wisdom_{theme_choice.lower().replace(' ', '_')}.png", mime="image/png", use_container_width=True)
    with st.expander("👁️ Preview Card"):
        st.image(card_bytes, use_container_width=True)

st.markdown("""<div style='text-align: center; padding: 40px 20px; margin-top: 60px; opacity: 0.6;'><div style='font-size: 2rem; margin-bottom: 10px;'>🕉️</div><p style='font-size: 0.9rem; color: #64748b;'>May you find wisdom, peace, and purpose on your journey</p></div>""", unsafe_allow_html=True)