import streamlit as st
import sys
import os
import pandas as pd
import random
import textwrap
import time
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

# --- 1. PATH SETUP ---
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
sys.path.append(project_root)

try:
    from backend.rag_engine import generate_answer
except ImportError:
    st.error("⚠️ Backend not found.")

# Define paths
FONT_PATH = os.path.join(current_dir, 'font.ttf')
DATA_PATH = os.path.join(project_root, 'data', 'gita_verses.csv')

# --- 2. PAGE CONFIG ---
st.set_page_config(
    page_title="Saarthi (सारथी) 2.0",
    page_icon="☸️",
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- 3. HELPER: THEMED WISDOM CARDS ---
def create_quote_image(text, theme="Mystic Blue"):
    img_width, img_height = 800, 800
    
    # Theme Color Maps (Top Color -> Bottom Color)
    themes = {
        "Mystic Blue": ((30, 41, 59), (76, 29, 149)),        # Original
        "Saffron Sunset": ((255, 140, 0), (139, 0, 0)),      # Orange/Red
        "Forest Peace": ((20, 50, 20), (50, 100, 50)),       # Deep Greens
        "Galaxy Void": ((0, 0, 0), (75, 0, 130))             # Black/Purple
    }
    
    top_color, bottom_color = themes.get(theme, themes["Mystic Blue"])

    img = Image.new('RGB', (img_width, img_height), top_color)
    draw = ImageDraw.Draw(img)

    for y in range(img_height):
        r = int(top_color[0] + (bottom_color[0] - top_color[0]) * y / img_height)
        g = int(top_color[1] + (bottom_color[1] - top_color[1]) * y / img_height)
        b = int(top_color[2] + (bottom_color[2] - top_color[2]) * y / img_height)
        draw.line([(0, y), (img_width, y)], fill=(r, g, b))

    try:
        font_large = ImageFont.truetype(FONT_PATH, 42)
        font_small = ImageFont.truetype(FONT_PATH, 24)
        font_header = ImageFont.truetype(FONT_PATH, 30)
    except:
        font_large = ImageFont.load_default()
        font_small = ImageFont.load_default()
        font_header = ImageFont.load_default()

    clean_text = text.replace("**", "").replace("###", "").replace(":", "")
    if len(clean_text) > 280: clean_text = clean_text[:280] + "..."
    wrapper = textwrap.TextWrapper(width=30) 
    word_list = wrapper.wrap(text=clean_text)

    margin = 60
    current_h = 120
    draw.text((margin, 50), "☸️ SAARTHI WISDOM", fill=(255, 215, 0), font=font_header)

    for line in word_list:
        draw.text((margin, current_h), line, font=font_large, fill=(255, 255, 255))
        bbox = font_large.getbbox(line)
        line_height = bbox[3] if bbox else 20
        current_h += line_height + 15 

    draw.text((margin, img_height - 80), "Generated by Saarthi AI", fill=(200, 200, 200), font=font_small)

    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()

@st.cache_data(ttl=3600)
def get_random_shloka():
    if not os.path.exists(DATA_PATH): return None
    try:
        df = pd.read_csv(DATA_PATH)
        if df.empty: return None
        row = df.sample(1).iloc[0]
        return {"text": str(row['sanskrit']).strip(), "meaning": str(row['translation']), "ref": f"Gita {row['chapter']}.{row['verse']}"}
    except: return None

# --- 4. CSS STYLING ---
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Martel:wght@300;400;800&family=Poppins:wght@300;400;600&display=swap');
.stApp { background: linear-gradient(135deg, #fffbf0 0%, #f3e8ff 100%); }
.stChatMessage p, .stMarkdown p { color: #1e293b !important; }
h1, h2, h3, h4, span, div { font-family: 'Poppins', sans-serif; }
.stChatMessage { border-radius: 16px; font-family: 'Martel', serif; }
.stChatMessage.user { background-color: #fff7ed !important; border-left: 4px solid #d97706; }
.stChatMessage.assistant { background-color: #f5f3ff !important; border-left: 4px solid #7c3aed; }
.header-box { background: linear-gradient(135deg, #1e293b 0%, #4c1d95 100%); padding: 30px; border-radius: 20px; text-align: center; margin-bottom: 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.15); }
.header-title { color: white !important; font-size: 2.5rem; font-weight: 700; }
.header-subtitle { color: #e2e8f0 !important; font-size: 1rem; font-style: italic; }

/* Breathing Animation */
@keyframes breathe {
  0% { transform: scale(1); opacity: 0.8; }
  50% { transform: scale(1.2); opacity: 1; }
  100% { transform: scale(1); opacity: 0.8; }
}
.breathing-circle {
  width: 150px; height: 150px; background-color: #fbbf24; border-radius: 50%;
  margin: 0 auto; animation: breathe 4s infinite ease-in-out;
  display: flex; align-items: center; justify-content: center;
  color: #78350f; font-weight: bold; font-size: 1.2rem;
}
</style>
""", unsafe_allow_html=True)

# --- 5. SIDEBAR: SADHANA & SETTINGS ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3663/3663344.png", width=80)
    st.markdown("## Saarthi 2.0")
    
    # 1. Sadhana Streak (Gamification)
    st.markdown("### 🔥 My Sadhana")
    st.progress(70)
    st.caption("Day 7 of 10: 'Conquering Anger'")
    
    # 2. Settings
    st.markdown("### ⚙️ Settings")
    language = st.radio("Language:", ["English", "Hindi"])
    mode = st.radio("Level:", ["Beginner", "Scholar"])
    
    # 3. Focus Mode (New Feature)
    st.markdown("### 🎯 Focus Mode")
    focus = st.selectbox("I am asking about:", ["General", "Relationships", "Work/Career", "Self-Growth"])
    
    st.divider()
    daily = get_random_shloka()
    if daily:
        st.info(f"**✨ Morning Mantra**\n\n{daily['text']}")

# --- 6. MAIN HEADER & SOS BUTTON ---
col_head, col_sos = st.columns([3, 1])
with col_head:
    st.markdown("""
    <div class="header-box">
        <div class="header-title">Saarthi (सारथी)</div>
        <div class="header-subtitle">Your Companion for Dharma, Artha, Kama, Moksha</div>
    </div>
    """, unsafe_allow_html=True)

with col_sos:
    # INSTANT CALM BUTTON
    if st.button("🆘 CALM ME", type="primary", help="Start 2-minute breathing"):
        st.session_state.calm_mode = True

# --- 7. BREATHING MODE (OVERLAY) ---
if st.session_state.get("calm_mode", False):
    st.markdown("## 🧘 Instant Calm (Pranayama)")
    placeholder = st.empty()
    bar = st.progress(0)
    
    for i in range(1, 4): # 3 Cycles
        placeholder.markdown(f"""
        <div style="text-align:center;">
            <h3>Cycle {i}/3</h3>
            <div class="breathing-circle">Inhale...</div>
        </div>
        """, unsafe_allow_html=True)
        time.sleep(4)
        
        placeholder.markdown(f"""
        <div style="text-align:center;">
            <h3>Cycle {i}/3</h3>
            <div class="breathing-circle" style="background-color: #818cf8; transform: scale(1.2);">Hold...</div>
        </div>
        """, unsafe_allow_html=True)
        time.sleep(4)
        
        placeholder.markdown(f"""
        <div style="text-align:center;">
            <h3>Cycle {i}/3</h3>
            <div class="breathing-circle" style="transform: scale(0.8);">Exhale...</div>
        </div>
        """, unsafe_allow_html=True)
        time.sleep(4)
        bar.progress(i * 33)

    st.success("You are calm. You are strong. Return to your duty.")
    if st.button("Close"):
        st.session_state.calm_mode = False
        st.rerun()

# --- 8. CHAT INTERFACE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# Empty State with Focus-Aware Prompts
if not st.session_state.messages and not st.session_state.get("calm_mode", False):
    st.markdown(f"### 🧭 Start a Journey ({focus} Mode):")
    c1, c2, c3 = st.columns(3)
    
    # Dynamic Prompts based on Focus
    if focus == "Relationships":
        p1, p2, p3 = "How to handle family conflict?", "Duties of a parent?", "Dealing with loneliness?"
    elif focus == "Work/Career":
        p1, p2, p3 = "How to handle failure?", "Leadership lessons?", "Focus at work?"
    else:
        p1, p2, p3 = "Mental Peace", "Understand Karma", "Start Meditation"

    if c1.button(f"✨ {p1}"): 
        st.session_state.messages.append({"role": "user", "content": p1})
        st.rerun()
    if c2.button(f"⚔️ {p2}"): 
        st.session_state.messages.append({"role": "user", "content": p2})
        st.rerun()
    if c3.button(f"🌿 {p3}"): 
        st.session_state.messages.append({"role": "user", "content": p3})
        st.rerun()

# Display History
for msg in st.session_state.messages:
    avatar = "https://cdn-icons-png.flaticon.com/512/4140/4140048.png" if msg["role"] == "user" else "https://cdn-icons-png.flaticon.com/512/3663/3663344.png"
    with st.chat_message(msg["role"], avatar=avatar):
        st.markdown(msg["content"])

# Input
if prompt := st.chat_input("Ask Saarthi..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.rerun()

# Generation (Only runs if NEW message)
if st.session_state.messages and st.session_state.messages[-1]["role"] == "user":
    with st.chat_message("assistant", avatar="https://cdn-icons-png.flaticon.com/512/3663/3663344.png"):
        with st.spinner("Consulting the Shastras..."):
            history = [{"role": m["role"], "content": m["content"]} for m in st.session_state.messages]
            
            answer, sources = generate_answer(
                st.session_state.messages[-1]["content"], 
                history[:-1], 
                mode=mode, 
                language=language,
                focus=focus
            )
            
            full_response = answer
            if sources:
                header = "**📚 Reference:**"
                full_response += f"\n\n---\n{header}\n" + "\n".join([f"- {s}" for s in sources])
            
            st.markdown(full_response)
            
    # Append to history immediately
    st.session_state.messages.append({"role": "assistant", "content": full_response})
    st.rerun()  # FORCE RE-RUN TO SHOW THE CARD CONTROLS BELOW

# --- 9. PERSISTENT CARD GENERATOR (The Fix) ---
# This block runs OUTSIDE the generation loop.
# It checks: If the last message is from Assistant -> Show Card Controls.
if st.session_state.messages and st.session_state.messages[-1]["role"] == "assistant":
    last_response = st.session_state.messages[-1]["content"]
    
    st.divider()
    st.markdown("#### 🎴 Wisdom Card Studio")
    
    c_theme, c_btn = st.columns([2, 1])
    with c_theme:
        # Changing this triggers a rerun, but since we are outside the 'if user' block,
        # it will just redraw this section with the new theme!
        theme_choice = st.selectbox("Select Theme:", ["Mystic Blue", "Saffron Sunset", "Forest Peace", "Galaxy Void"])
    
    with c_btn:
        # Generate card on the fly based on current theme
        # Clean text for the card (remove citations)
        card_text = last_response.split("**📚 Reference:**")[0].strip()
        card_bytes = create_quote_image(card_text, theme=theme_choice)
        
        st.download_button(
            label="📸 Download Card", 
            data=card_bytes, 
            file_name="saarthi_card.png", 
            mime="image/png"
        )