import streamlit as st
import sys
import os
import pandas as pd
import random
import textwrap
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

# --- PATH SETUP ---
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from backend.rag_engine import generate_answer

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Saarthi (सारथी) 2.0",
    page_icon="☸️",
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- HELPER: GENERATE QUOTE CARD WITH GRADIENT ---
def create_quote_image(text):
    img_width = 800
    img_height = 800
    
    # 1. Create Gradient Background (Top Color -> Bottom Color)
    # Top: Deep Spiritual Blue | Bottom: Rich Purple/Saffron tone
    top_color = (30, 41, 59)  # Dark slate blueish
    bottom_color = (76, 29, 149) # Deep purple

    img = Image.new('RGB', (img_width, img_height), top_color)
    draw = ImageDraw.Draw(img)

    # Manually draw linear gradient by interpolating colors vertically
    for y in range(img_height):
        r = int(top_color[0] + (bottom_color[0] - top_color[0]) * y / img_height)
        g = int(top_color[1] + (bottom_color[1] - top_color[1]) * y / img_height)
        b = int(top_color[2] + (bottom_color[2] - top_color[2]) * y / img_height)
        draw.line([(0, y), (img_width, y)], fill=(r, g, b))

    # 2. Load Font
    try:
        # Ensure 'font.ttf' is inside the frontend folder
        font_path = os.path.join(os.path.dirname(__file__), 'font.ttf') 
        # Use a large font for the main text
        font = ImageFont.truetype(font_path, 42)
        # Smaller font for footer
        footer_font = ImageFont.truetype(font_path, 24)
        header_font = ImageFont.truetype(font_path, 30)
    except:
        # Fallback if custom font missing
        font = ImageFont.load_default()
        footer_font = ImageFont.load_default()
        header_font = ImageFont.load_default()

    # 3. Wrap & Clean Text
    # Remove markdown bolding
    clean_text = text.replace("**", "").replace("###", "").replace(":", "")
    # Cap length to fit nicely
    if len(clean_text) > 280:
        clean_text = clean_text[:280] + "..."
    
    # Wrap text at approx 30 characters
    wrapper = textwrap.TextWrapper(width=30) 
    word_list = wrapper.wrap(text=clean_text)

    # 4. Draw Content onto Gradient
    margin = 60
    current_h = 120

    # Header (Gold color for contrast)
    draw.text((margin, 50), "☸️ SAARTHI WISDOM", fill=(251, 191, 36), font=header_font)

    # Body text (White color for maximum contrast on dark gradient)
    for line in word_list:
        draw.text((margin, current_h), line, font=font, fill=(255, 255, 255))
        # Calculate line height based on font size for better spacing
        current_h += font.getbbox(line)[3] + 15 

    # Footer (Light Grey)
    draw.text((margin, img_height - 80), "Generated by Saarthi AI • Your Digital Charioteer", fill=(200, 200, 200), font=footer_font)

    # 5. Save to buffer
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()

# --- FAMOUS QUOTES ---
FAMOUS_QUOTES = [
    {"sanskrit": "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।", "english": "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action.", "ref": "Gita 2.47"},
    {"sanskrit": "न जायते म्रियते वा कदाचि-", "english": "The soul is neither born, nor does it ever die.", "ref": "Gita 2.20"},
    {"sanskrit": "योगः कर्मसु कौशलम् ।", "english": "Yoga is excellence in action.", "ref": "Gita 2.50"},
    {"sanskrit": "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत ।", "english": "Whenever there is a decline in righteousness, O Arjuna, I manifest Myself.", "ref": "Gita 4.7"},
    {"sanskrit": "संशयात्मा विनश्यति ।", "english": "The person who doubts is ruined.", "ref": "Gita 4.40"}
]

# --- GLOBAL THEME / CSS (App Background Gradient) ---
st.markdown("""
<style>
/* Import Fonts */
@import url('https://fonts.googleapis.com/css2?family=Martel:wght@300;400;800&family=Merriweather:ital,wght@0,300;0,400;0,700;1,300&family=Poppins:wght@300;400;600&display=swap');

/* Main Background - Spiritual Soft Gradient */
.stApp {
    background: linear-gradient(135deg, #fffbf0 0%, #f3e8ff 100%); /* Light Orange to Light Purple */
}

/* Force Text Colors to Dark for Readability */
.stApp, .stMarkdown, p, h1, h2, h3, h4, h5, h6, span, div, li { color: #1e293b !important; }
section[data-testid="stSidebar"] p, section[data-testid="stSidebar"] span, section[data-testid="stSidebar"] div, section[data-testid="stSidebar"] h1, section[data-testid="stSidebar"] h2, section[data-testid="stSidebar"] label { color: #f1f5f9 !important; }

/* Fonts Styling */
h1, h2, h3 { font-family: 'Poppins', sans-serif; color: #3d342b !important; }
.sanskrit-text { font-family: 'Martel', serif; font-weight: 800; color: #8b4513 !important; }

/* Chat Bubbles */
.stChatMessage { background-color: rgba(255, 255, 255, 0.95) !important; border: 1px solid #e2e8f0; border-radius: 16px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); font-family: 'Merriweather', serif; }
.stChatMessage p, .stChatMessage div { color: #000000 !important; }
.stChatMessage.user { background: linear-gradient(135deg, #fff7ed 0%, #ffffff 100%) !important; border-left: 4px solid #d97706; } /* Orange Tint */
.stChatMessage.assistant { background: linear-gradient(135deg, #f5f3ff 0%, #ffffff 100%) !important; border-left: 4px solid #7c3aed; } /* Purple Tint */

/* Input & Buttons */
textarea, input { background-color: #ffffff !important; color: #000000 !important; border: 1px solid #cbd5e1 !important; border-radius: 12px; padding: 10px; }
div.stButton > button { width: 100%; border-radius: 12px; height: 3.8em; font-weight: 600; background-color: #ffffff; color: #4b5563 !important; border: 1px solid #e5e7eb; box-shadow: 0 4px 6px rgba(0,0,0,0.04); transition: all 0.3s ease; }
div.stButton > button:hover { border-color: #d97706; color: #d97706 !important; background-color: #fffbf0; transform: translateY(-2px); box-shadow: 0 6px 8px rgba(0,0,0,0.08); }

/* Header Box */
.header-box { background: linear-gradient(135deg, #1e293b 0%, #4c1d95 100%); padding: 35px; border-radius: 20px; text-align: center; margin-bottom: 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.15); color: white !important;}
.header-box div, .header-box p, .header-box h1 { color: #ffffff !important; }
.header-title { font-size: 2.8rem; font-weight: 700; letter-spacing: 1px; margin-bottom: 8px; }
.header-subtitle { font-size: 1.1rem; font-weight: 300; opacity: 0.95; font-style: italic; }
.header-sanskrit { font-family: 'Martel', serif; font-size: 1.2rem; color: #fbbf24 !important; margin-top: 20px; font-weight: 600;}

/* Sidebar */
section[data-testid="stSidebar"] { background: linear-gradient(180deg, #111827 0%, #1e1e2e 100%); }
</style>
""", unsafe_allow_html=True)

# --- HELPER: RANDOM SHLOKA ---
@st.cache_data(ttl=3600)
def get_random_shloka():
    try:
        data_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'gita_verses.csv')
        df = pd.read_csv(data_path)
        if not df.empty:
            row = df.sample(1).iloc[0]
            raw_sanskrit = row['sanskrit'].replace('\n', ' ').replace('|', '').strip()
            return {"text": raw_sanskrit, "meaning": row['translation'], "ref": f"Gita {row['chapter']}.{row['verse']}"}
    except:
        return None

# --- SIDEBAR ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3663/3663344.png", width=80)
    st.markdown("<h2 style='color: white !important;'>Saarthi 2.0</h2>", unsafe_allow_html=True)
    st.caption("☸️ Your Digital Charioteer")
    
    st.markdown("### 🎚️ Complexity Level")
    mode = st.radio("Select your path:", ["Beginner", "Scholar"], 
                    captions=["Simple analogies & daily life", "Deep philosophy & Sanskrit terms"])
    st.divider()
    
    daily_shloka = get_random_shloka()
    if daily_shloka:
        st.markdown(f"""
        <div style="background: rgba(255,255,255,0.08); padding: 20px; border-radius: 15px; border: 1px solid rgba(255,255,255,0.1); margin-top: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
            <p style="color: #94a3b8 !important; font-size: 0.75rem; margin:0; text-transform: uppercase; letter-spacing: 1.5px; font-weight: 600;">✨ Daily Wisdom</p>
            <p style="color: #fbbf24 !important; font-family: 'Martel', serif; font-size: 1.1rem; line-height: 1.6; margin: 15px 0; font-weight: 600;">{daily_shloka['text']}</p>
            <p style="color: #e2e8f0 !important; font-size: 0.9rem; font-style: italic; line-height: 1.5;">"{daily_shloka['meaning'][:120]}..."</p>
            <div style="text-align: right; color: #9ca3af !important; font-size: 0.8rem; margin-top: 10px; font-weight: 500;">— {daily_shloka['ref']}</div>
        </div>
        """, unsafe_allow_html=True)
    st.divider()
    if st.button("🔄 Reset Chat"):
        st.session_state.messages = []
        st.rerun()

# --- HERO SECTION ---
quote = random.choice(FAMOUS_QUOTES)
st.markdown(f"""
<div class="header-box">
    <div class="header-title">Saarthi (सारथी)</div>
    <div class="header-subtitle">Your guide through the battlefield of life</div>
    <div class="header-sanskrit">{quote['sanskrit']}</div>
    <div style="font-size: 1rem; margin-top: 8px; color: #e2e8f0 !important;">"{quote['english']}"</div>
</div>
""", unsafe_allow_html=True)

# --- CHAT LOGIC ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# Learning Paths (Empty State)
if len(st.session_state.messages) == 0:
    st.markdown("### 🧭 Start a Journey:")
    col1, col2, col3 = st.columns(3)
    start_prompt = None
    with col1:
        if st.button("🧘 Mental Peace\n\nOvercome anxiety"): start_prompt = "I am feeling anxious. What does the Gita say about finding peace?"
    with col2:
        if st.button("⚔️ Duty & Career\n\nUnderstand Karma"): start_prompt = "I am confused about my career. Explain Karma Yoga."
    with col3:
        if st.button("🕉️ Meditation\n\nStart practice"): start_prompt = "How should a beginner start meditation?"
    if start_prompt:
        st.session_state.messages.append({"role": "user", "content": start_prompt})
        st.rerun()

# Display Chat
for message in st.session_state.messages:
    if message["role"] == "user":
        avatar_url = "https://cdn-icons-png.flaticon.com/512/4140/4140048.png"
    else:
        avatar_url = "https://cdn-icons-png.flaticon.com/512/3663/3663344.png"
    
    with st.chat_message(message["role"], avatar=avatar_url):
        st.markdown(message["content"])

# Handle Input
if prompt := st.chat_input("Arjuna asks Krishna..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.rerun()

# GENERATE ANSWER & SHARE CARD LOGIC
if st.session_state.messages and st.session_state.messages[-1]["role"] == "user":
    with st.chat_message("assistant", avatar="https://cdn-icons-png.flaticon.com/512/3663/3663344.png"):
        with st.spinner(f"The Charioteer is contemplating ({mode} Mode)..."):
            user_query = st.session_state.messages[-1]["content"]
            history_for_ai = [{"role": m["role"], "content": m["content"]} for m in st.session_state.messages[:-1]]
            
            # Generate
            answer, sources = generate_answer(user_query, history_for_ai, mode=mode)
            full_response = answer
            if sources: full_response += "\n\n---\n**📚 Shastra Pramana:**\n" + "\n".join([f"- {s}" for s in sources])
            st.markdown(full_response)
            
            # Create Card (Uses new gradient function)
            card_bytes = create_quote_image(answer)
            st.download_button(
                label="📸 Download Wisdom Card",
                data=card_bytes,
                file_name="saarthi_wisdom.png",
                mime="image/png"
            )

    st.session_state.messages.append({"role": "assistant", "content": full_response})